name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/MvcToTheCloud/
    - name: Build
      run: dotnet build --no-restore ./src/MvcToTheCloud/
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/MvcToTheCloud/
    - name: Generate package
      run: dotnet publish ./src/MvcToTheCloud/MvcToTheCloud/MvcToTheCloud.csproj -o ./publish --configuration Release

    - name: Zip package
      uses: papeloto/action-zip@v1
        with:
          files: ./publish
          dest: publish.zip

    - name: Login to azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/azuredeploy.json
        parameters: ./infra/azuredeploy.parameters.json
